# Generated by Django 3.1.6 on 2021-02-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='8e51a1606e7d43918697296f75a5fbc6', max_length=100),
        ),
    ]
