# Generated by Django 3.1.6 on 2021-03-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210303_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='cd968fb36a2f4573814bc9a62bda4d97', max_length=100),
        ),
    ]
