# Generated by Django 3.1.6 on 2021-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210303_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='be57492e4df04ef8a26df6f188087996', max_length=100),
        ),
    ]
