# Generated by Django 3.1.6 on 2021-03-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210303_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='3704dce276e24d31a83be4c47635b960', max_length=100),
        ),
    ]
