# Generated by Django 3.1.6 on 2021-03-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210303_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='462de92161df46479d67fd103d95fd0b', max_length=100),
        ),
    ]
