# Generated by Django 3.1.6 on 2021-03-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210303_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='3c917b061458404b9188ad039543c3e4', max_length=100),
        ),
    ]
