# Generated by Django 3.1.6 on 2021-03-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210303_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='5a7186eeccee4686947c0e5517bd470b', max_length=100),
        ),
    ]
