# Generated by Django 3.1.6 on 2021-03-04 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0011_auto_20210303_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='83167348eb8c4c0a9d9e5c1a6ba66e16', max_length=100),
        ),
    ]
