# Generated by Django 3.1.6 on 2021-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210303_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='bc021b7e333043d4a650e463bfd1c6c8', max_length=100),
        ),
    ]
