# Generated by Django 3.0.8 on 2021-03-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210305_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='065df4909a7542a7ac1480f836b48888', max_length=100),
        ),
    ]
