# Generated by Django 3.0.8 on 2021-03-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210305_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default='3b30c6766e5a4e08a0c764213030b984', max_length=100),
        ),
    ]
