# Generated by Django 3.0.8 on 2021-03-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20210305_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='namespace',
            field=models.CharField(default="b'NTI2YmEyOTRkOTI4NDEwMzkxNDliZDgwNDUwZWUwOGY3b3dDaVVGMW1hUlBYQ205Z2tFWnVRdFJ5MUF1Z1VCZ2c5aVBROTZlcnE4SkVqVGhCNDIwMjEtMDMtMTkgMTg6MDU6NDAuOTQwMjU4'", max_length=500),
        ),
    ]
